// Bilingual copy. SV is canonical (matches flyer), EN is translation.
window.STRINGS = {
  sv: {
    nav: {
      about: "Om tjänsten",
      services: "Hjälp med",
      pricing: "Pris & område",
      book: "Boka tid",
      contact: "Kontakt",
    },
    hero: {
      eyebrow: "Trygghet, närvaro och enkelhet",
      title1: "Privat",
      title2: "vardagshjälp",
      title3: "för äldre",
      lede: "Jag erbjuder privat vardagshjälp för äldre som vill ha extra stöd i livet — utan krångel eller biståndsbeslut. Du bestämmer själv hur mycket hjälp du behöver.",
      ctaBook: "Boka en tid",
      ctaCall: "Ring 070 202 74 94",
      badge: ["Trygghet, närvaro", "och enkelhet", "utan krångel"],
    },
    about: {
      eyebrow: "Om tjänsten",
      title: "En lugn hand i vardagen",
      p1: "Jag erbjuder privat vardagshjälp för äldre som vill ha extra stöd i livet.",
      p2: "Fokus ligger på trygghet, närvaro och enkelhet — utan krångel eller biståndsbeslut.",
      p3: "Du bestämmer själv hur mycket hjälp du behöver, och vi anpassar oss efter ditt tempo.",
    },
    services: {
      eyebrow: "Jag erbjuder hjälp med",
      title: "Det vardagen behöver",
      lede: "Fem områden där jag gärna lättar bördan — välj det du behöver, och kombinera fritt.",
      items: [
        { name: "Lättare hushållssysslor", desc: "Städning, tvätt, bäddning, disk, inköp m.m." },
        { name: "Ledsagning och skjuts till läkare", desc: "Följer med och skjutsar till läkarbesök eller andra ärenden." },
        { name: "Hjälp med ärenden", desc: "Jag hjälper till med matinköp, apoteksbesök, postärenden och annat som underlättar." },
        { name: "Sällskap", desc: "Trevligt sällskap, samtal, promenader och aktiviteter utifrån dina önskemål." },
        { name: "Tillsyn", desc: "Trygg tillsyn i hemmet — jag finns där när du behöver mig." },
      ],
    },
    info: {
      priceLabel: "Pris",
      priceText: "Från 350 kr/timme före RUT-avdrag. Med RUT blir kostnaden oftast cirka hälften.",
      areaLabel: "Område",
      areaText: "Uppsala, Knivsta och Tierp med omnejd.",
      rutTitle: "Vad är RUT-avdrag?",
      rutText: "RUT är en svensk skattereduktion för hushållsnära tjänster — staten betalar upp till 50 % av arbetskostnaden direkt till mig, så du får hälften av priset dragen från fakturan. Du behöver inte göra något själv; jag sköter administrationen.",
    },
    booking: {
      eyebrow: "Boka tid",
      title: "Hitta en tid som passar",
      lede: "Fyll i några korta uppgifter så återkommer jag samma dag med en bekräftelse.",
      steps: ["Tjänst", "Tid", "Kontakt", "Bekräfta"],
      step1Title: "Vad vill du ha hjälp med?",
      step1Sub: "Välj en eller flera. Du kan alltid ändra senare.",
      step2Title: "När passar det?",
      step2Sub: "Välj en preliminär tid — vi bekräftar tillsammans efteråt.",
      step3Title: "Hur når jag dig?",
      step3Sub: "Jag återkommer med bekräftelse via telefon eller mejl.",
      step4Title: "Stämmer detta?",
      step4Sub: "Ingenting bokas innan jag har bekräftat med dig personligen.",
      labels: {
        name: "Namn",
        phone: "Telefon",
        email: "E-post",
        notes: "Något jag bör veta? (frivilligt)",
        notesPh: "Särskilda önskemål, hur jag bäst kommer in i hemmet, etc.",
        forWho: "Bokar du åt dig själv eller någon annan?",
        forSelf: "För mig själv",
        forOther: "För en närstående",
        firstTime: "Är detta första gången?",
        yes: "Ja, första gången",
        no: "Nej, vi har talats vid förut",
      },
      back: "Tillbaka",
      next: "Nästa",
      send: "Skicka förfrågan",
      booking: "Skickar…",
      successTitle: "Tack — din förfrågan är skickad",
      successText: "Jag svarar gärna med namn, behov och önskad tid så återkommer jag snabbt. Du hör från mig inom dagen.",
      successAgain: "Boka en till tid",
      summary: {
        services: "Tjänster",
        date: "Datum",
        time: "Tid",
        name: "Namn",
        phone: "Telefon",
        email: "E-post",
        notes: "Övrigt",
        forWho: "Bokar för",
      },
      months: ["januari", "februari", "mars", "april", "maj", "juni", "juli", "augusti", "september", "oktober", "november", "december"],
      dows: ["mån", "tis", "ons", "tor", "fre", "lör", "sön"],
      err: {
        services: "Välj minst en tjänst.",
        date: "Välj ett datum.",
        time: "Välj en tid.",
        name: "Ange namn.",
        contact: "Ange telefon eller e-post.",
        email: "Ogiltig e-postadress.",
      },
    },
    contact: {
      title: "Kontakta mig!",
      name: "Julia Hedström",
      phone: "070 202 74 94",
      email: "Hedstromjulia7@gmail.com",
      quote: "Skriv gärna namn, behov och önskad tid så återkommer jag snabbt.\n\n",
    },
    footer: "Privat vardagshjälp för äldre · Uppsala, Knivsta & Tierp · Alltid med",
  },

  en: {
    nav: {
      about: "About",
      services: "Services",
      pricing: "Price & area",
      book: "Book",
      contact: "Contact",
    },
    hero: {
      eyebrow: "Calm, presence, and simplicity",
      title1: "Private",
      title2: "everyday help",
      title3: "for elders",
      lede: "I offer private everyday help for elders who want a little extra support — no red tape, no eligibility process. You decide how much help you need.",
      ctaBook: "Book a time",
      ctaCall: "Call 070 202 74 94",
      badge: ["Calm, presence", "and simplicity", "no fuss"],
    },
    about: {
      eyebrow: "About the service",
      title: "A steady hand for the everyday",
      p1: "I offer private everyday help for elders who want a little extra support in life.",
      p2: "The focus is on calm, presence, and simplicity — without paperwork or eligibility decisions.",
      p3: "You decide how much help you need, and we move at your pace.",
    },
    services: {
      eyebrow: "I can help with",
      title: "What the day needs",
      lede: "Five areas where I'm glad to lighten the load — pick what you need, mix freely.",
      items: [
        { name: "Light household tasks", desc: "Cleaning, laundry, bed-making, dishes, groceries." },
        { name: "Company to medical visits", desc: "I come along and drive you to doctor appointments or other errands." },
        { name: "Help with errands", desc: "Grocery runs, pharmacy visits, post office, and other things that make life easier." },
        { name: "Companionship", desc: "Pleasant company, conversation, walks, and activities you'd enjoy." },
        { name: "Check-in visits", desc: "A reassuring presence in the home — I'm there when you need me." },
      ],
    },
    info: {
      priceLabel: "Price",
      priceText: "From 350 SEK/hour before RUT deduction. With RUT, your cost is typically about half.",
      areaLabel: "Area",
      areaText: "Uppsala, Knivsta and Tierp and surrounding areas.",
      rutTitle: "What is RUT-avdrag?",
      rutText: "RUT is a Swedish tax deduction for household services — the state pays up to 50 % of the labor cost directly to me, so you only see half on the invoice. You don't need to do anything yourself; I handle the paperwork.",
    },
    booking: {
      eyebrow: "Book a time",
      title: "Find a time that suits",
      lede: "Fill in a few quick details and I'll get back to you the same day with a confirmation.",
      steps: ["Service", "Time", "Contact", "Confirm"],
      step1Title: "What can I help you with?",
      step1Sub: "Pick one or more. You can change it later.",
      step2Title: "When works for you?",
      step2Sub: "Choose a preliminary time — we'll confirm together afterwards.",
      step3Title: "How can I reach you?",
      step3Sub: "I'll get back to you by phone or email with a confirmation.",
      step4Title: "Does this look right?",
      step4Sub: "Nothing is booked until I've confirmed with you personally.",
      labels: {
        name: "Name",
        phone: "Phone",
        email: "Email",
        notes: "Anything I should know? (optional)",
        notesPh: "Specific preferences, how to best enter the home, etc.",
        forWho: "Are you booking for yourself or someone else?",
        forSelf: "For myself",
        forOther: "For a loved one",
        firstTime: "Is this the first time?",
        yes: "Yes, first time",
        no: "No, we've spoken before",
      },
      back: "Back",
      next: "Next",
      send: "Send request",
      booking: "Sending…",
      successTitle: "Thank you — your request has been sent",
      successText: "I'll reach out with a confirmation soon. You'll hear from me within the day.",
      successAgain: "Book another time",
      summary: {
        services: "Services",
        date: "Date",
        time: "Time",
        name: "Name",
        phone: "Phone",
        email: "Email",
        notes: "Notes",
        forWho: "Booking for",
      },
      months: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
      dows: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
      err: {
        services: "Please select at least one service.",
        date: "Please choose a date.",
        time: "Please choose a time.",
        name: "Please enter a name.",
        contact: "Please enter a phone number or email.",
        email: "Please enter a valid email address.",
      },
    },
    contact: {
      title: "Get in touch!",
      name: "Julia Hedström",
      phone: "070 202 74 94",
      email: "Hedstromjulia7@gmail.com",
      quote: "I'll happily reply with names, needs, and a preferred time — and get back to you quickly.",
    },
    footer: "Private everyday help for elders · Uppsala, Knivsta & Tierp · Always with care",
  },
};
